import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";
import { createElement as h } from "react";
import { renderToStaticMarkup } from "react-dom/server";
import { MantineProvider } from "@mantine/core";

import { compareRuns } from "../src/experiments/compare/api.ts";
import { CompareReport } from "../src/experiments/compare/ComparePanel.tsx";
import {
  compareErrorMessage, measureHeadlines, sideLine, validateCompare, verdictOf, type CompareResult, type EngineCompare,
} from "../src/experiments/compare/model.ts";
import { engineLeaves } from "../src/experiments/replay/model.ts";

// Generated by `python3 tests/test_studio_compare.py --write`: the compare route's payload, which
// that test checks against `citizen runs compare --json` and `replay_stats.compare` on the same rows.
const fixture = JSON.parse(readFileSync(new URL("./fixtures/compare.json", import.meta.url), "utf8")) as CompareResult;

function render(result: CompareResult): string {
  return renderToStaticMarkup(h(MantineProvider, {}, h(CompareReport, { result })));
}

function clone<T>(value: T): T {
  return JSON.parse(JSON.stringify(value)) as T;
}

test("every field of the engine's output is displayed unchanged", () => {
  assert.ok(fixture.comparable);
  const leaves = engineLeaves(fixture.result);
  const html = render(fixture);
  for (const [path, value] of leaves) {
    assert.ok(html.includes(path), path);
    assert.ok(html.includes(value.replace(/"/g, "&quot;")), `${path} ${value}`);
  }
});

test("each headline carries the engine's reading, interval and trial counts verbatim", () => {
  const arm = fixture.result!.arms![0];
  const headlines = measureHeadlines(fixture.result, fixture.preferred);
  assert.equal(headlines.length, Object.keys(arm.measures).length);
  for (const item of headlines) {
    const measure = arm.measures[item.key];
    assert.equal(item.reading, measure.reading);
    assert.ok(item.line.includes(`interval ${JSON.stringify(measure.interval)}`), item.line);
    assert.ok(item.line.includes(`n ${measure.n} against ${measure.control_n}`), item.line);
    assert.ok(item.line.includes(`${arm.trials} paired trial(s) per task over ${arm.tasks} task(s)`), item.line);
    if (measure.estimate !== null) assert.ok(item.line.includes(`estimate ${JSON.stringify(measure.estimate)}`), item.line);
  }
  const costOfPass = headlines.find((item) => item.key === "cost_per_passed")!;
  assert.match(costOfPass.line, /^cost per passed attempt: lower \(better\); estimand "measured"; /);
  assert.equal(costOfPass.direction, "better");
  assert.ok(arm.exploratory);
  for (const item of headlines) assert.ok(item.line.includes(`exploratory: ${arm.exploratory_reasons.join("; ")}`), item.line);
  const html = render(fixture);
  assert.match(html, /The engine marks candidate exploratory: fewer than 5 paired trials per task \(2\)/);
});

test("a ratio whose interval spans one shows the engine's inconclusive, whatever its estimate", () => {
  const result = clone(fixture.result) as EngineCompare;
  const measure = result.arms![0].measures.cost_per_passed;
  Object.assign(measure, { estimate: 0.85, effect: -0.15, interval: [-0.55, 0.45], reading: "inconclusive",
    reason: "the interval spans no effect" });
  const item = measureHeadlines(result, fixture.preferred).find((entry) => entry.key === "cost_per_passed")!;
  const line = item.line;
  assert.equal(item.direction, null);
  assert.match(line, /^cost per passed attempt: inconclusive; estimand "measured"; estimate 0\.85, effect -0\.15; interval \[-0\.55,0\.45\]/);
  assert.match(line, /the interval spans no effect$/);
});

test("an interval the engine could not give stays visible as null with its reason", () => {
  const line = measureHeadlines(fixture.result).find((item) => item.key === "turns")!.line;
  assert.match(line, /^turns: unavailable; estimand "measured"; estimate null, effect absent; interval null at confidence 0\.95/);
  assert.match(line, /lack turns$/);
});

test("the preferred direction labels a reading better or worse, never flat", () => {
  assert.deepEqual(verdictOf("lower", "lower"), { label: "lower (better)", direction: "better" });
  assert.deepEqual(verdictOf("lower", "higher"), { label: "lower (worse)", direction: "worse" });
  assert.deepEqual(verdictOf("higher", "higher"), { label: "higher (better)", direction: "better" });
  assert.deepEqual(verdictOf("inconclusive", "lower"), { label: "inconclusive", direction: null });
  assert.deepEqual(verdictOf("lower", undefined), { label: "lower", direction: null });
  const worse = clone(fixture);
  worse.direction_withheld = [];
  Object.assign(worse.result!.arms![0].measures.pass_rate, { reading: "lower" });
  const html = render(worse);
  assert.match(html, /lower \(worse\)/);
  assert.match(html, /lower \(better\)/);
  assert.doesNotMatch(html, /flat/);
  assert.doesNotMatch(html, /cost: lower \(/);
  const soft = clone(fixture);
  Object.assign(soft.result!.arms![0].measures.first_call_context, { estimand: "soft estimate" });
  assert.match(measureHeadlines(soft.result, soft.preferred).find((entry) => entry.key === "first_call_context")!.line,
    /estimand "soft estimate"/);
});

test("an exploratory or undated-window result shows the plain reading and says why", () => {
  assert.ok(fixture.direction_withheld.length > 0);
  const html = render(fixture);
  assert.doesNotMatch(html, /\((better|worse)\)/);
  assert.match(html, /cost per passed attempt: lower; /);
  assert.match(html, /No reading is labelled better or worse: the base is exploratory; the candidate is exploratory; the engine marks candidate exploratory\./);
  const dated = { ...clone(fixture), notes: ["different run dates: the base ran 2026-09-01, the candidate 2026-10-01"] };
  assert.match(render(dated), /different run dates: the base ran 2026-09-01, the candidate 2026-10-01/);
});

test("a refused comparison names every difference and shows no figures", () => {
  const refused = { ...clone(fixture), comparable: false, result: null,
    refusals: ["different task sets: only the base runs c; only the candidate runs d"] };
  const html = render(refused);
  assert.match(html, /Not compared/);
  assert.match(html, /different task sets: only the base runs c; only the candidate runs d/);
  assert.doesNotMatch(html, /Engine output/);
  assert.deepEqual(measureHeadlines(null), []);
});

test("both sides show their identity, their own analysis and a stale draft", () => {
  const stale = clone(fixture);
  stale.candidate = { ...stale.candidate, stale: true, freshness: "stale", stale_reason: "the draft has a newer checkpoint" };
  stale.stale = ["candidate: the draft has a newer checkpoint"];
  const html = render(stale);
  assert.match(html, /Stale: candidate: the draft has a newer checkpoint/);
  assert.match(sideLine(stale.candidate), /Stale: the draft has a newer checkpoint\.$/);
  assert.match(html, /This target against its own bare arm/);
  assert.match(sideLine(fixture.base), /^Run 0{8}-0{4}-4000-8000-0{11}1, target 1: branch main at a{12}; 3 task\(s\), claude-test, 2 trial\(s\), exploratory\. Freshness not checked\.$/);
  assert.match(sideLine({ ...fixture.base, freshness: "current" }), / Current\.$/);
});

test("the form asks only with two run ids, and names each refusal code", () => {
  assert.deepEqual(validateCompare({ base: { run_id: "", target: 1 }, candidate: { run_id: fixture.base.run_id, target: 2 } }),
    ["The base needs a run id."]);
  assert.deepEqual(validateCompare({ base: { run_id: fixture.base.run_id, target: 1 }, candidate: { run_id: fixture.base.run_id, target: 2 } }), []);
  assert.equal(compareErrorMessage("compare_not_finished"), "Both runs must have finished before they are compared.");
  assert.equal(compareErrorMessage("other"), "The comparison could not be read (other).");
});

test("the comparison posts both sides to the fixed CSRF route", async () => {
  const original = globalThis.fetch;
  const calls: Array<{ input: string; init?: RequestInit }> = [];
  globalThis.fetch = (async (input: string | URL | Request, init?: RequestInit) => {
    calls.push({ input: String(input), init });
    if (String(input) === "/api/session") return new Response(JSON.stringify({ csrf_token: "csrf" }), { status: 200 });
    return new Response(JSON.stringify(fixture), { status: 200 });
  }) as typeof fetch;
  try {
    const value = await compareRuns({ base: { run_id: ` ${fixture.base.run_id} `, target: 1 },
      candidate: { run_id: fixture.candidate.run_id, target: 2 } });
    assert.equal(value.engine, "replay_stats.compare");
  } finally {
    globalThis.fetch = original;
  }
  assert.equal(calls[1].input, "/api/runs/compare");
  assert.equal((calls[1].init?.headers as Record<string, string>)["X-Studio-CSRF"], "csrf");
  assert.deepEqual(JSON.parse(String(calls[1].init?.body)), {
    base: { run_id: fixture.base.run_id, target: 1 }, candidate: { run_id: fixture.candidate.run_id, target: 2 } });
});
