import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";
import { createElement as h } from "react";
import { renderToStaticMarkup } from "react-dom/server";
import { MantineProvider } from "@mantine/core";

import { DraftTest, RegistrationList, VerdictCard } from "../src/configure/DraftTest.tsx";
import { registerDraftTest, startDraftTest } from "../src/configure/draftTestApi.ts";
import {
  currentRegistration, draftTestErrorMessage, evidenceBadge, initialForm, registerBody, startBlocked, startedMessage,
  type DraftTestRegistration, type DraftTestVerdicts,
} from "../src/configure/draftTestModel.ts";

// Generated by `python3 tests/test_studio_draft_tests.py --write` (see draft-test.test.ts).
const fixture = JSON.parse(readFileSync(new URL("./fixtures/draft-test.json", import.meta.url), "utf8")) as DraftTestVerdicts;

function clone<T>(value: T): T {
  return JSON.parse(JSON.stringify(value)) as T;
}

function registration(changes: Partial<DraftTestRegistration> = {}): DraftTestRegistration {
  return {
    registration_id: "22222222-2222-4222-8222-222222222222", draft: "tuned", draft_id: "id",
    revision: fixture.revision, config_digest: null, base_revision: fixture.base_revision, model: "claude-test",
    tasks: ["b", "a"], repetitions: 5, pack: null, manifest_digest: "d".repeat(64), effect: 0.15, cv: 0.1,
    power: fixture.checkpoints[0].latest.power, plan: "benchmarks/preregistrations/2026-10-03-draft-x.md",
    plan_commit: "f".repeat(40), plan_sha256: "e".repeat(64), created_at: "2026-10-03T00:00:00+00:00",
    stale: false, stale_reason: null, problems: [], used_by: null, ...changes,
  };
}

function page(element: ReturnType<typeof h>): string {
  return renderToStaticMarkup(h(MantineProvider, {}, element));
}

test("the register body fixes the sample and the effect, never a caller's cv", () => {
  const form = { ...initialForm("claude-test", null), tasks: ["a", "b"], cv: "0.1" };
  assert.deepEqual(registerBody("tuned", form), {
    draft: "tuned", effect: 0.15, cv: null,
    request: { model: "claude-test", repetitions: 5, tasks: ["a", "b"], pack: null },
  });
});

test("only the newest current, intact, unused registration is used", () => {
  const verdicts = clone(fixture);
  verdicts.registrations = [registration({ stale: true, stale_reason: "the draft has a newer checkpoint" }),
    registration({ registration_id: "used", used_by: "run" }), registration({ registration_id: "intact" })];
  assert.equal(currentRegistration(verdicts)?.registration_id, "intact");
  verdicts.registrations[2].problems = ["the plan differs from the text registered"];
  assert.equal(currentRegistration(verdicts), null);
});

test("pre-register ticked with no current registration blocks the start", () => {
  assert.equal(startBlocked(true, null), "Register the test before you start it, or untick pre-register.");
  assert.equal(startBlocked(true, registration()), null);
  assert.equal(startBlocked(false, null), null);
});

test("a stale or altered registration stays listed and is marked", () => {
  const html = page(h(RegistrationList, { registrations: [
    registration({ stale: true, stale_reason: "the draft has a newer checkpoint" }),
    registration({ registration_id: "other", problems: ["the plan differs from the text registered"] }),
    registration({ registration_id: "third", used_by: "run-1" }),
  ] }));
  assert.ok(html.includes("Backs run"), html);
  assert.ok(html.includes("Stale: the draft has a newer checkpoint; register the test again."), html);
  assert.ok(html.includes("Not intact"));
  assert.ok(html.includes("the plan differs from the text registered"));
  assert.ok(page(h(RegistrationList, { registrations: [] })).includes("No registrations of this draft yet."));
});

test("a verdict says whether its run counted as pre-registered", () => {
  const item = clone(fixture.checkpoints[0].latest);
  assert.deepEqual(evidenceBadge(item), { label: "Exploratory", variant: "light" });
  item.registration = "r"; item.deviations = ["the run's model differs from the registration's"];
  assert.equal(evidenceBadge(item).label, "Registered, deviated: exploratory");
  item.evidence = "pre-registered"; item.verdict = "helped"; item.deviations = [];
  const html = page(h(VerdictCard, { test: item, current: true, count: 1 }));
  assert.ok(html.includes("Pre-registered"));
  assert.ok(html.includes("Helped"));
  assert.equal(draftTestErrorMessage("draft_test_registration_stale"),
    "The draft changed since it was registered; register the test again.");
});

test("register posts to its CSRF route and start names the registration only when given", async () => {
  const original = globalThis.fetch;
  const calls: Array<{ input: string; init?: RequestInit }> = [];
  globalThis.fetch = (async (input: string | URL | Request, init?: RequestInit) => {
    calls.push({ input: String(input), init });
    if (String(input) === "/api/session") return new Response(JSON.stringify({ csrf_token: "csrf" }), { status: 200 });
    return new Response(JSON.stringify({ registration: registration(), power_line: "", run_id: "x", status: "queued" }), { status: 200 });
  }) as typeof fetch;
  try {
    await registerDraftTest({ draft: "tuned" });
    await startDraftTest("tuned", { model: "m" } as never, "token", 0.15, null, "r");
  } finally {
    globalThis.fetch = original;
  }
  const posts = calls.filter((call) => call.input !== "/api/session");
  assert.deepEqual(posts.map((call) => call.input), ["/api/configure/test/register", "/api/configure/test/start"]);
  for (const call of posts) assert.equal((call.init?.headers as Record<string, string>)["X-Studio-CSRF"], "csrf");
  assert.equal(JSON.parse(String(posts[1].init?.body)).registration, "r");
});

test("the started message comes from the server's record, never assumed", () => {
  const run = { run_id: "r1", status: "queued" };
  assert.match(startedMessage({ ...run, record: { registration: "g", deviations: [] } }), /pre-registered: it matches/);
  const lost = startedMessage({ ...run, record: { registration: "g", deviations: ["the run's task manifest differs from the registration's"] } });
  assert.match(lost, /exploratory: the run's task manifest differs/);
  assert.ok(!/pre-registered/.test(lost));
  assert.match(startedMessage({ ...run, record: { registration: null, deviations: [] } }), /, exploratory\./);
});

test("the blocked-start live region is mounted before it has anything to say", () => {
  const html = page(h(DraftTest, { draft: "tuned", revision: "rev" }));
  assert.ok((html.match(/aria-live="polite"/g) ?? []).length >= 3, html);
  assert.ok(draftTestErrorMessage("draft_test_variance_undeclared").includes("benchmarks/ablations.json"));
});
