import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";
import { createElement as h } from "react";
import { renderToStaticMarkup } from "react-dom/server";
import { MantineProvider } from "@mantine/core";

import { VerdictCard } from "../src/configure/DraftTest.tsx";
import { loadDraftVerdicts, planDraftTest, startDraftTest } from "../src/configure/draftTestApi.ts";
import {
  draftTestErrorMessage, initialForm, planBody, readingLines, spendLine, validateDraftTest, verdictBadge,
  withNeededTrials, type DraftTestVerdict, type DraftTestVerdicts,
} from "../src/configure/draftTestModel.ts";

// Generated by `python3 tests/test_studio_draft_tests.py --write`: the verdicts route's payload for
// a draft tested at one checkpoint and since changed, which that test checks against
// `citizen draft test --json` and #990's comparison of the same run.
const fixture = JSON.parse(readFileSync(new URL("./fixtures/draft-test.json", import.meta.url), "utf8")) as DraftTestVerdicts;

function clone<T>(value: T): T {
  return JSON.parse(JSON.stringify(value)) as T;
}

function render(item: DraftTestVerdict, current = false): string {
  return renderToStaticMarkup(h(MantineProvider, {}, h(VerdictCard, { test: item, current, count: 1 })));
}

test("a checkpoint's verdict shows its headline, readings, spend, power and comparison", () => {
  const entry = fixture.checkpoints[0];
  const html = render(entry.latest);
  assert.equal(entry.latest.verdict, "exploratory");
  assert.ok(html.includes("Exploratory: no claim"), html);
  assert.ok(html.includes(entry.latest.revision.slice(0, 12)));
  assert.ok(html.includes(entry.latest.comparison.command));
  assert.ok(html.includes("Open comparison"));
  assert.ok(html.includes(spendLine(entry.latest)));
  assert.ok(html.includes(entry.latest.power_line.replace(/'/g, "&#x27;")));
  for (const reason of entry.latest.reasons) assert.ok(html.includes(reason), reason);
});

test("a draft changed after its test marks the verdict stale in the agreed words", () => {
  const item = fixture.checkpoints[0].latest;
  assert.equal(item.stale, true);
  const html = render(item);
  assert.ok(html.includes("Stale: the draft changed after this comparison."));
  assert.ok(html.includes("Verdict stale"));
  const fresh = clone(item);
  fresh.stale = false; fresh.stale_copy = null; fresh.stale_reason = null;
  assert.ok(!render(fresh).includes("Verdict stale"));
});

test("readings are the engine's, with interval and counts and never a direction", () => {
  const item = fixture.checkpoints[0].latest;
  const lines = readingLines(item);
  assert.equal(lines.length, Object.keys(item.readings).length);
  for (const [key, measure] of Object.entries(item.readings)) {
    const line = lines.find((entry) => entry.startsWith(key === "pass_rate" ? "Pass rate" : "Cost-of-Pass"))!;
    assert.ok(line.includes(`interval ${JSON.stringify(measure.interval)}`), line);
    assert.ok(line.includes(`n ${measure.n} against ${measure.control_n}`), line);
    assert.ok(!/better|worse/.test(line), line);
  }
});

test("only helped and worse badges differ from the neutral one", () => {
  assert.deepEqual(verdictBadge("helped"), { label: "Helped", color: "teal", variant: "filled" });
  assert.deepEqual(verdictBadge("worse"), { label: "Worse", color: "red", variant: "outline" });
  for (const name of ["exploratory", "inconclusive", "running", "not_compared"] as const) {
    assert.equal(verdictBadge(name).variant, "light");
  }
});

test("too few trials offers the number needed, and the form takes it", () => {
  const power = fixture.checkpoints[0].latest.power;
  assert.equal(power.enough, false);
  assert.ok(power.needed_trials !== null);
  const form = { ...initialForm("claude-test", null), repetitions: 2, tasks: ["a"] };
  assert.equal(withNeededTrials(form, power).repetitions, power.needed_trials);
  assert.ok(fixture.checkpoints[0].latest.power_line.includes(`run ${power.needed_trials} trials per task instead`));
});

test("the form is validated and becomes the plan body with the effect as a fraction", () => {
  const form = { ...initialForm("claude-test", null), tasks: ["a"], effect_percent: 15, cv: "" };
  assert.deepEqual(validateDraftTest(form), []);
  assert.deepEqual(planBody("tuned", form), {
    draft: "tuned",
    request: { model: "claude-test", repetitions: 5, tasks: ["a"], max_budget_usd: "2", spend_cap_usd: "20", pack: null },
    effect: 0.15, cv: null,
  });
  assert.equal(planBody("tuned", { ...form, cv: "0.3" }).cv, 0.3);
  assert.deepEqual(validateDraftTest({ ...form, tasks: [], effect_percent: 0, cv: "x", repetitions: 21 }), [
    "Choose at least one task.", "Trials per task must be a whole number from 1 to 20.",
    "The change worth detecting must be above 0% and below 100%.",
    "The coefficient of variation must be above 0 and at most 10, or left empty."]);
  assert.equal(draftTestErrorMessage("draft_test_mismatch"), "The draft changed since the plan; check power and spend again.");
  assert.equal(draftTestErrorMessage("other"), "The draft test was refused (other).");
});

test("plan, start and verdicts post to their fixed CSRF routes", async () => {
  const original = globalThis.fetch;
  const calls: Array<{ input: string; init?: RequestInit }> = [];
  globalThis.fetch = (async (input: string | URL | Request, init?: RequestInit) => {
    calls.push({ input: String(input), init });
    if (String(input) === "/api/session") return new Response(JSON.stringify({ csrf_token: "csrf" }), { status: 200 });
    return new Response(JSON.stringify(fixture), { status: 200 });
  }) as typeof fetch;
  try {
    await planDraftTest({ draft: "tuned" });
    await startDraftTest("tuned", { model: "m" } as never, "token", 0.15, null);
    const value = await loadDraftVerdicts("tuned");
    assert.equal(value.draft, fixture.draft);
  } finally {
    globalThis.fetch = original;
  }
  const posts = calls.filter((call) => call.input !== "/api/session");
  assert.deepEqual(posts.map((call) => call.input),
    ["/api/configure/test/plan", "/api/configure/test/start", "/api/configure/test/verdicts"]);
  for (const call of posts) assert.equal((call.init?.headers as Record<string, string>)["X-Studio-CSRF"], "csrf");
  assert.deepEqual(JSON.parse(String(posts[1].init?.body)),
    { draft: "tuned", request: { model: "m" }, confirmation_token: "token", effect: 0.15, cv: null });
  assert.deepEqual(JSON.parse(String(posts[2].init?.body)), { draft: "tuned" });
});
