import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";

import { analysisLines, engineLeaves, type ReplayAnalysis } from "../src/experiments/replay/model.ts";

// Generated by `python3 tests/test_studio_replay_analysis_parity.py --write`: the result route's
// analysis for real `cost_bench.py summarise --json` output, which that test checks against the CLI.
const fixture = JSON.parse(readFileSync(new URL("./fixtures/replay-analysis.json", import.meta.url), "utf8")) as ReplayAnalysis[];

function leaves(value: unknown, path: string, out: Map<string, unknown>): void {
  if (value !== null && typeof value === "object" && !(Array.isArray(value) && value.every((v) => v === null || typeof v !== "object"))) {
    const entries = Array.isArray(value) ? value.map((v, i) => [`[${i}]`, v] as const) : Object.entries(value);
    for (const [key, item] of entries) leaves(item, key.startsWith("[") ? `${path}${key}` : path ? `${path}.${key}` : key, out);
    return;
  }
  out.set(path, value);
}

test("every engine value in the route's analysis is displayed unchanged", () => {
  assert.equal(fixture.length, 2);
  for (const entry of fixture) {
    const expected = new Map<string, unknown>();
    leaves(entry.result, "", expected);
    const shown = new Map(analysisLines(entry));
    assert.equal(shown.size, expected.size);
    for (const [path, value] of expected) {
      assert.equal(shown.get(path), JSON.stringify(value), path);
      assert.deepEqual(JSON.parse(shown.get(path) as string), value, path);
    }
  }
});

test("the fields a fixed list dropped are all displayed", () => {
  const shown = new Map(analysisLines(fixture[0]));
  for (const prefix of ["long", "delegation", "arms.bare.pass_rate_interval_descriptive", "undefined_resamples", "arms.harness.mean_cost_per_attempt"]) {
    assert.ok([...shown.keys()].some((key) => key === prefix || key.startsWith(prefix + ".") || key.startsWith(prefix + "[")), prefix);
  }
  const undefinedRatio = new Map(analysisLines(fixture[1]));
  assert.equal(undefinedRatio.get("ratio"), "null");
  assert.notEqual(undefinedRatio.get("ratio_undefined"), "null");
});

test("an engine refusal and empty containers stay visible", () => {
  assert.deepEqual(analysisLines({ target: 1, error: "cost-bench: no rows" }), [["Engine refused", "cost-bench: no rows"]]);
  assert.deepEqual(engineLeaves({ long: {}, tasks: [] }), [["long", "{}"], ["tasks", "[]"]]);
});

test("the cache basis and the oracle's named metrics are displayed", () => {
  const shown = new Map(analysisLines(fixture[0]));
  assert.equal(shown.get("cache_basis"), JSON.stringify("shared"));
  assert.equal(shown.get("metrics.metrics.accuracy.direction"), JSON.stringify("higher"));
  assert.ok(shown.has("metrics.metrics.accuracy.difference_interval"));
  assert.equal(new Map(analysisLines(fixture[1])).has("metrics.metrics.accuracy.direction"), false);
});
