import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";
import { createElement as h } from "react";
import { renderToStaticMarkup } from "react-dom/server";
import { MantineProvider } from "@mantine/core";
import { MemoryRouter } from "react-router-dom";

import { RuleHealthReport, TriedDraft } from "../src/reports/rules/RuleHealthPage.tsx";
import {
  effectText, hitLine, lastFiredText, reliability, sortRows, summaryLine, tokensText, tryWithoutErrorMessage, windowText,
  type RuleHealth, type RuleRow, type TryWithoutResult,
} from "../src/reports/rules/model.ts";

// Generated by `python3 tests/test_studio_rule_health.py --write`: the rule-health route's payload
// over fixed engine documents, which that test also checks `report()` still produces.
const fixture = JSON.parse(readFileSync(new URL("./fixtures/rule-health.json", import.meta.url), "utf8")) as RuleHealth;

function row(name: string): RuleRow {
  const found = fixture.rows.find((item) => item.rule === name);
  assert.ok(found, name);
  return found;
}

function render(health: RuleHealth): string {
  return renderToStaticMarkup(h(MantineProvider, {}, h(MemoryRouter, {},
    h(RuleHealthReport, { health, onTry: () => undefined, trying: null }))));
}

test("every rule shows the status and reason the engine reported", () => {
  const html = render(fixture);
  for (const item of fixture.rows) {
    assert.ok(html.includes(`>${item.state}<`), item.rule);
    if (item.reason) assert.ok(html.includes(item.reason.replace(/'/g, "&#x27;")), item.reason);
  }
  assert.ok(html.includes(`rules: ${summaryLine(fixture)}`));
  assert.equal(summaryLine(fixture), "3 measured, 1 dark, 1 unmeasured (60% measured)");
});

test("a detector under the precision floor marks the rule's hit figures unreliable", () => {
  const voice = row("voice-and-format");
  const check = reliability(voice.hits);
  assert.deepEqual(check, { label: "unreliable", tone: "danger", reason: "voice/banned-opener precision 0.75 is under the 0.90 floor" });
  const html = render(fixture);
  assert.ok(html.includes("Hit figures unreliable: voice/banned-opener precision 0.75 is under the 0.90 floor"));
  assert.equal(reliability(row("secrets").hits)?.label, "precision at floor");
});

test("hit figures are the engine's counts, labelled exploratory, never inverted into followed", () => {
  const voice = row("voice-and-format");
  assert.equal(windowText(voice.hits, 30), "6/40 (15%)");
  assert.equal(hitLine("voice/banned-opener", voice.hits.windows["30"].detectors["voice/banned-opener"]),
    "voice/banned-opener: fired in 6 of 40 sessions (15%), 9 hits");
  assert.equal(lastFiredText(voice.hits, fixture.windows), "within 7 days");
  assert.equal(voice.hits.label, "exploratory");
  const html = render(fixture);
  assert.ok(html.includes(fixture.exploratory_note.replace(/'/g, "&#x27;")));
  assert.ok(!/\bfollowed in\b/.test(html));
});

test("a rule with no evidence says not measured with its reason, never zero", () => {
  const dark = row("conciseness");
  assert.equal(windowText(dark.hits, 7), "not measured");
  assert.equal(lastFiredText(dark.hits, fixture.windows), "not measured");
  assert.equal(effectText(dark.effect), "not measured: no ablation run has removed this module");
  assert.equal(tokensText(row("working-style").tokens), "not measured: the scorecard reads not loaded");
  assert.equal(tokensText(dark.tokens), "218 tokens (soft estimate)");
  assert.equal(effectText(row("secrets").effect), "cost -4.0% [-9.0%, 1.0%], n 6, inconclusive (arm no-secrets)");
});

test("Try without it is offered on a switched-on rule and explained elsewhere", () => {
  const html = render(fixture);
  assert.ok(html.includes('aria-label="Try without conciseness"'));
  assert.ok(!html.includes('aria-label="Try without working-style"'));
  assert.ok(html.includes(row("autonomy").try_without.reason));
  assert.equal(sortRows(fixture.rows)[0].rule, "conciseness");
  assert.match(tryWithoutErrorMessage("rule-not-switchable"), /not switched on/);
});

test("a tried draft shows its CLI steps and its draft test, ready to run", () => {
  const result: TryWithoutResult = {
    schema_version: 1, rule: "conciseness", draft: { name: "without-conciseness-1a2b3c4d", revision: "a".repeat(40) },
    changes: { "rules.conciseness": "off" },
    commands: ["citizen draft create without-conciseness-1a2b3c4d --json", "citizen draft selection save without-conciseness-1a2b3c4d"],
    message: "Draft without-conciseness-1a2b3c4d switches conciseness off. Nothing live changed.",
  };
  const html = renderToStaticMarkup(h(MantineProvider, {}, h(MemoryRouter, {}, h(TriedDraft, { result }))));
  assert.ok(html.includes("Nothing live changed."));
  for (const command of result.commands) assert.ok(html.includes(command));
  assert.ok(html.includes("Open drafts in Configure"));
});

test("an unreadable source is named and its column reads not measured", () => {
  const partial = JSON.parse(JSON.stringify(fixture)) as RuleHealth;
  partial.status = "partial";
  partial.sources.cost = { status: "unavailable", message: "citizen scorecard timed out" };
  const html = render(partial);
  assert.ok(html.includes("cost: citizen scorecard timed out"));
});
