import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";
import { createElement as h } from "react";
import { renderToStaticMarkup } from "react-dom/server";
import { MantineProvider } from "@mantine/core";
import { MemoryRouter } from "react-router-dom";

import { TrendsReport } from "../src/reports/trends/TrendsPage.tsx";
import { delegationText, extent, figureText, proofSummary, sm2Text, statusText, type Trends } from "../src/reports/trends/model.ts";

// Generated by `python3 tests/test_studio_trends.py --write`: the trends route's payload over fixed
// history rows and a verified bundle, which that test also checks `report()` still produces.
const fixture = JSON.parse(readFileSync(new URL("./fixtures/trends.json", import.meta.url), "utf8")) as Trends;

function render(trends: Trends, measure = "ratio_sm2"): string {
  return renderToStaticMarkup(h(MantineProvider, {}, h(MemoryRouter, {},
    h(TrendsReport, { trends, measure, onMeasure: () => undefined }))));
}

function line(id: string) {
  const found = fixture.lines.find((item) => item.id === id);
  assert.ok(found, id);
  return found;
}

test("each series plots by version and date with its change notes", () => {
  const html = render(fixture, "ratio");
  const points = line("replay-v2").points;
  assert.deepEqual(points.map((point) => point.harness_version), ["0.13.0", "0.14.0", "0.15.0"]);
  for (const point of points) {
    assert.ok(html.includes(`${point.harness_version} · ${point.date}`), point.date ?? "");
    assert.ok(html.includes(point.change_note), point.change_note);
  }
  assert.ok(html.includes("Series replay-v2"));
  assert.ok(html.includes("Series micro-v1"));
  // One polyline per line, joining only that line's points.
  assert.equal((html.match(/<polyline/g) ?? []).length, fixture.lines.length);
  assert.ok(html.includes(">1.052<") || html.includes(">1.052 "));
});

test("ratios are compared across days, never dollars", () => {
  const html = render(fixture, "ratio");
  assert.ok(html.includes("never dollars"));
  assert.ok(!html.includes("$"));
  assert.ok(!/\bUSD\b/.test(html));
});

test("a stored interval is drawn and stated; a point without one draws none", () => {
  const html = render(fixture, "ratio_sm2");
  const first = line("replay-v2").points[0].measures.ratio_sm2;
  assert.ok(first.interval);
  assert.ok(html.includes(`data-low="${first.interval[0]}"`));
  assert.ok(html.includes(`data-high="${first.interval[1]}"`));
  assert.equal(figureText(first), "1.042 (SM-2 interval 0.942 to 1.142)");
  // Two replay-v2 points carry an SM-2 interval; the 0.14.0 ratio is undefined and the micro row stored none.
  assert.equal((html.match(/class="trend-interval"/g) ?? []).length, 2);
  assert.equal(figureText(line("replay-v2").points[1].measures.ratio_sm2), "undefined: bare passed nothing");
  assert.ok(html.includes("undefined: bare passed nothing"));
  const plain = render(fixture, "ratio");
  assert.equal((plain.match(/class="trend-interval"/g) ?? []).length, 0);
  assert.equal(figureText(line("replay-v2").points[0].measures.pass_rate_harness), "0.85 (descriptive interval 0.65 to 0.95)");
  assert.deepEqual(extent(line("replay-v2").points, "ratio_sm2"), [0.8, 1.142]);
});

test("every point is labelled exploratory or pre-registered and an exploratory line says so", () => {
  const html = render(fixture, "ratio");
  assert.ok(html.includes(line("replay-v2").evidence_note));
  assert.ok(html.includes(line("micro-v1").evidence_note));
  assert.ok(line("micro-v1").evidence_note.includes("exploratory"));
  assert.ok(html.includes("pre-registered (docs/plans/registered.md)"));
  // The chart's one visual cue: an exploratory point is hollow, a pre-registered one filled.
  const circles = [...html.matchAll(/<g data-evidence="([a-z-]+)"[^]*?<circle[^>]*fill="([^"]+)"/g)].map((match) => [match[1], match[2]]);
  assert.equal(circles.length, 4);
  for (const [evidence, fill] of circles) assert.equal(fill, evidence === "exploratory" ? "none" : "currentColor", evidence);
  assert.ok(circles.some(([evidence]) => evidence === "exploratory"));
  assert.ok(circles.some(([evidence]) => evidence === "pre-registered"));
});

test("SM-2's own verdict, reason and claim are shown, qualified when exploratory", () => {
  const [registered, exploratory] = line("replay-v2").points;
  assert.equal(sm2Text(registered), "SM-2 eligibility: eligible. verdict: inconclusive, because the ratio interval spans 1");
  assert.equal(sm2Text(exploratory), "SM-2 eligibility: eligible. verdict: supported (exploratory, not from a registered run), "
    + "because both conditions of the decision rule hold; claim: the harness costs less per pass");
  assert.ok(delegationText(exploratory).includes("exploratory, not from a registered run"));
  assert.equal(sm2Text(line("micro-v1").points[0]), "SM-2 unavailable: the rows saved no pass or fail");
  const html = render(fixture);
  assert.ok(html.includes("verdict: supported (exploratory, not from a registered run)"));
});

test("the proof bundle shows its verify status and claims as citizen evidence verify reports them", () => {
  const html = render(fixture);
  const bundle = fixture.proof.bundles[0];
  assert.equal(bundle.status, "verified");
  assert.ok(html.includes(bundle.command));
  assert.ok(html.includes("Observed cost ratio"));
  assert.ok(html.includes("unknown, not verified: reasoning effort for the bare arm"));
  assert.ok(html.includes("in the bundle, not published"));
  assert.ok(html.includes("0.7 to 0.95"));
  assert.equal(proofSummary(fixture.proof), "1 published claim(s): 1 verified now by citizen evidence verify, 0 not verified.");
  const none = { ...fixture, proof: { statement: "The project publishes no measured claim: product.json binds no evidence card.", claims: [], bundles: [] } };
  assert.ok(render(none).includes("The project publishes no measured claim"));
});

test("a card in a failed bundle never shows verified", () => {
  const bundle = fixture.proof.bundles[0];
  const cards = bundle.cards.map((card) => ({ ...card, verified: false }));
  const failed = { ...fixture, proof: { ...fixture.proof,
    claims: fixture.proof.claims.map((claim) => ({ ...claim, status: "failed" as const, reason: "its bundle failed verification" })),
    bundles: [{ ...bundle, status: "failed" as const, errors: ["item 3: plan is missing"], cards }] } };
  const html = render(failed);
  assert.ok(html.includes(">failed<"));
  assert.ok(html.includes("item 3: plan is missing"));
  assert.ok(html.includes("not verified (bundle failed)"));
  assert.ok(!/data-tone="success">verified</.test(html));
});

test("a claim no check ran on reads not verified (no check ran), distinct from failed", () => {
  assert.equal(statusText("not checked"), "not verified (no check ran)");
  const proof = { statement: null, bundles: [{ ...fixture.proof.bundles[0], status: "not checked" as const, reason: "past the page's limit of 16 bundles", cards: [], bundle_id: null }],
    claims: [{ ...fixture.proof.claims[0], status: "not checked" as const, reason: "past the page's limit of 16 bundles" }] };
  const html = render({ ...fixture, proof });
  assert.ok(html.includes("not verified (no check ran)"));
  assert.ok(html.includes("past the page&#x27;s limit of 16 bundles"));
  assert.equal(proofSummary(proof), "1 published claim(s): 0 verified now by citizen evidence verify, 0 not verified, 1 not verified (no check ran).");
});

test("a section the run index cannot give says so and the proof set still shows", () => {
  const sections = { history: { status: "unavailable" as const, reason: "the run index could not be read: locked", unreadable: 0, truncated: false },
    static: { status: "ready" as const, reason: null, unreadable: 2, truncated: true } };
  const html = render({ ...fixture, lines: [], sections });
  assert.ok(html.includes("Benchmark history could not be read; the rest of the page still shows"));
  assert.ok(html.includes("the run index could not be read: locked"));
  assert.ok(html.includes(`Static context: only the newest ${fixture.max_records} records are shown`));
  assert.ok(html.includes("Static context: 2 record(s) could not be read"));
  assert.ok(html.includes("The project&#x27;s proof set"));
  assert.ok(!html.includes("No benchmark history is indexed"));
});

test("an empty index says so instead of drawing a line", () => {
  const html = render({ ...fixture, lines: [] });
  assert.ok(html.includes("No benchmark history is indexed"));
  assert.ok(!html.includes("<polyline"));
});
