import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";
import { createElement as h } from "react";
import { renderToStaticMarkup } from "react-dom/server";
import { MantineProvider } from "@mantine/core";
import { MemoryRouter } from "react-router-dom";

import { TrendsReport } from "../src/reports/trends/TrendsPage.tsx";
import { extent, figureText, proofSummary, sm2Text, type Trends } from "../src/reports/trends/model.ts";

// Generated by `python3 tests/test_studio_trends.py --write`: the trends route's payload over fixed
// history rows and a verified bundle, which that test also checks `report()` still produces.
const fixture = JSON.parse(readFileSync(new URL("./fixtures/trends.json", import.meta.url), "utf8")) as Trends;

function render(trends: Trends, measure = "ratio_sm2"): string {
  return renderToStaticMarkup(h(MantineProvider, {}, h(MemoryRouter, {},
    h(TrendsReport, { trends, measure, onMeasure: () => undefined }))));
}

function line(id: string) {
  const found = fixture.lines.find((item) => item.id === id);
  assert.ok(found, id);
  return found;
}

test("each series plots by version and date with its change notes", () => {
  const html = render(fixture, "ratio");
  const points = line("replay-v2").points;
  assert.deepEqual(points.map((point) => point.harness_version), ["0.13.0", "0.14.0", "0.15.0"]);
  for (const point of points) {
    assert.ok(html.includes(`${point.harness_version} · ${point.date}`), point.date ?? "");
    assert.ok(html.includes(point.change_note), point.change_note);
  }
  assert.ok(html.includes("Series replay-v2"));
  assert.ok(html.includes("Series micro-v1"));
  // One polyline per line, joining only that line's points.
  assert.equal((html.match(/<polyline/g) ?? []).length, fixture.lines.length);
  assert.ok(html.includes(">1.052<") || html.includes(">1.052 "));
});

test("ratios are compared across days, never dollars", () => {
  const html = render(fixture, "ratio");
  assert.ok(html.includes("never dollars"));
  assert.ok(!html.includes("$"));
  assert.ok(!/\bUSD\b/.test(html));
});

test("a stored interval is drawn and stated; a point without one draws none", () => {
  const html = render(fixture, "ratio_sm2");
  const first = line("replay-v2").points[0].measures.ratio_sm2;
  assert.ok(first.interval);
  assert.ok(html.includes(`data-low="${first.interval[0]}"`));
  assert.ok(html.includes(`data-high="${first.interval[1]}"`));
  assert.equal(figureText(first), "1.042 (SM-2 interval 0.942 to 1.142)");
  // Three replay-v2 points carry an SM-2 interval; the micro row stored none.
  assert.equal((html.match(/class="trend-interval"/g) ?? []).length, 3);
  const plain = render(fixture, "ratio");
  assert.equal((plain.match(/class="trend-interval"/g) ?? []).length, 0);
  assert.equal(figureText(line("replay-v2").points[0].measures.pass_rate_harness), "0.85 (descriptive interval 0.65 to 0.95)");
  assert.deepEqual(extent(line("replay-v2").points, "ratio_sm2"), [0.8, 1.142]);
});

test("every point is labelled exploratory or pre-registered and an exploratory line says so", () => {
  const html = render(fixture);
  assert.ok(html.includes(line("replay-v2").evidence_note));
  assert.ok(html.includes(line("micro-v1").evidence_note));
  assert.ok(line("micro-v1").evidence_note.includes("exploratory"));
  assert.ok(html.includes("pre-registered (docs/plans/registered.md)"));
  assert.ok(html.includes('data-evidence="exploratory"'));
  assert.ok(html.includes('data-evidence="pre-registered"'));
});

test("SM-2's own verdict and reason are shown, never one made here", () => {
  const point = line("replay-v2").points[0];
  assert.equal(sm2Text(point), "SM-2 reads inconclusive; the ratio interval spans 1");
  assert.equal(sm2Text(line("micro-v1").points[0]), "SM-2 unavailable: the rows saved no pass or fail");
});

test("the proof bundle shows its verify status and claims as citizen evidence verify reports them", () => {
  const html = render(fixture);
  const bundle = fixture.proof.bundles[0];
  assert.equal(bundle.status, "verified");
  assert.ok(html.includes(bundle.command));
  assert.ok(html.includes("Observed cost ratio"));
  assert.ok(html.includes("unknown, not verified: reasoning effort for the bare arm"));
  assert.ok(html.includes("in the bundle, not published"));
  assert.ok(html.includes("0.7 to 0.95"));
  assert.equal(proofSummary(fixture.proof), "1 published claim(s); 1 verified now by citizen evidence verify.");
  const none = { ...fixture, proof: { statement: "The project publishes no measured claim: product.json binds no evidence card.", claims: [], bundles: [], unverified_bundles: [] } };
  assert.ok(render(none).includes("The project publishes no measured claim"));
  const failed = { ...fixture, proof: { ...fixture.proof, bundles: [{ ...bundle, status: "failed" as const, errors: ["item 3: plan is missing"] }] } };
  const failedHtml = render(failed);
  assert.ok(failedHtml.includes(">failed<"));
  assert.ok(failedHtml.includes("item 3: plan is missing"));
});

test("an empty index says so instead of drawing a line", () => {
  const html = render({ ...fixture, lines: [] });
  assert.ok(html.includes("No benchmark history is indexed"));
  assert.ok(!html.includes("<polyline"));
});
